In [1]:
#Para rodar os próximos comandos deve primeiro descompactar a pasta new_data encontrada no arquivo dados.zip

import zipfile

arquivo_zip = 'dados.zip'

with zipfile.ZipFile(arquivo_zip, 'r') as zip_ref:
    zip_ref.extractall('.')

Arquivos extraídos com sucesso!

In [2]:
import pandas as pd
import glob
import matplotlib.pyplot as plt

#Busca por todos arquivos que seguem o padrão descrito. O (*) pega desde o arquivo 00 até o 51
feature_files = glob.glob('new_data/TAG_iALL_PS_*.csv')

#Defino a lista que guardará as tabelas
list_dfs = []

#Loop para ler os arquivos e já transformar o timestamp em data e definir como índice
for files in feature_files:
    temp_df = pd.read_csv(files, index_col='timestamp', parse_dates=['timestamp'])
    list_dfs.append(temp_df)

feature_df = pd.concat(list_dfs, axis=1)
#Simplificando as variáveis para somente números
feature_df.columns = feature_df.columns.str.replace('TAG_iALL_PS_', '')

In [3]:
#Lendo e garantindo o index correto da variável target
target_df = pd.read_csv('new_data/target_iALL_PS.csv', index_col='timestamp', parse_dates=['timestamp'])

#Junção dos dois df
#'inner' vai garantir que somente as linhas(timestamp) presentes em ambas tabelas serão mantidas
final_df = feature_df.join(target_df, how='inner')

import os
if not os.path.exists('final_data'):
    os.makedirs('final_data')

final_df.to_csv('final_data/final_data.csv', index=False)

In [4]:
final_df.head()

,00,01,02,03,04,05,06,07,08,09,...,43,44,45,46,47,48,49,50,51,target_iALL_PS
timestamp,,,,,,,,,,,,,,,,,,,,,
2018-04-01 00:00:00,4.548754,90.886874,58.698896,89.301134,1011.733181,97.284889,33.248746,-10.390227,29.262578,43.896138,...,154.291476,114.466107,103.082616,119.246973,60.729332,310.022461,124.735196,426.651658,410.820484,NORMAL
2018-04-01 00:01:00,7.887998,56.555373,80.802810,120.898222,1358.466600,202.583688,32.494870,19.427739,61.038519,26.967553,...,59.239207,90.076161,93.760055,63.457947,62.910653,306.084796,158.822485,375.316113,143.620728,NORMAL
2018-04-01 00:02:00,4.975919,182.086958,87.273632,9.914782,1056.489015,147.098428,36.402837,38.900027,30.304666,45.272021,...,87.136301,99.274584,111.916792,60.560834,81.332910,353.863854,88.772027,444.809188,618.898000,NORMAL
2018-04-01 00:03:00,6.304142,58.417235,75.059520,64.167463,1619.924847,307.722320,34.283344,46.602862,44.859311,11.692485,...,110.321579,103.978381,103.705604,24.141894,36.219671,301.563110,53.387484,414.052496,427.323378,NORMAL
2018-04-01 00:04:00,1.671733,108.946809,94.910470,14.551922,591.648283,-7.684779,30.980682,39.293311,1.229287,43.643912,...,112.435498,103.170425,110.566095,53.913605,116.770552,298.957820,168.746952,431.548430,514.659884,NORMAL

In [5]:
final_df.tail()

,00,01,02,03,04,05,06,07,08,09,...,43,44,45,46,47,48,49,50,51,target_iALL_PS
timestamp,,,,,,,,,,,,,,,,,,,,,
2018-08-31 23:55:00,6.066461,128.157145,144.452803,66.621842,1791.181163,172.833101,13.116142,52.438915,32.694638,22.513291,...,105.953758,169.203415,74.959180,159.206995,98.736928,432.326663,199.902569,NaN,343.198701,NORMAL
2018-08-31 23:56:00,4.057784,-31.186502,49.775117,69.397205,1166.424000,146.161645,26.785100,17.436183,39.612008,45.942825,...,12.201309,59.127149,149.304241,26.936970,125.800942,402.294815,218.904951,NaN,381.082811,NORMAL
2018-08-31 23:57:00,6.751912,80.433446,107.038506,137.923928,1060.918628,106.901675,37.495990,20.406074,33.073722,45.243051,...,90.664739,144.615688,29.140853,118.974814,75.747273,269.339456,260.899365,NaN,452.482461,NORMAL
2018-08-31 23:58:00,2.084228,192.076427,125.030042,47.801000,1137.031690,202.800674,-2.724405,3.096265,40.085235,24.660919,...,29.244415,184.373135,126.818580,139.218900,50.266103,340.081930,208.046264,NaN,214.201448,NORMAL
2018-08-31 23:59:00,4.558682,16.293402,45.667827,95.239698,1797.283986,214.738743,45.953489,59.104965,9.853991,39.157247,...,98.999383,135.929342,23.427436,116.844695,128.664018,342.037875,252.498435,NaN,360.504647,NORMAL